### ISSUE TITLE
I get this error when clicking the mint button. (Metamask)

### ISSUE THREAD

**Issue by DiscrimIsPog** [fireship-io/web3-nft-dapp-tutorial#2]
![image](https://user-images.githubusercontent.com/61711429/150047021-b5e0496f-be9b-438d-9e9a-5d400110f023.png)

**Comment by DiscrimIsPog** [comment]
This is with a test wallet. Please let me know if others experience this issue with a test wallet, or if this is supposed to happen.

**Comment by codediodeio** [comment]
This came up for me a few times also. From Metamask, try **Settings -> Advanced -> Reset Account**

This should also work if you get an error saying "Nonce too high"

**Comment by DiscrimIsPog** [comment]
I just tried that, it unfortunately didn't work.

**Comment by GustantoC** [comment]
Idk If this is the solution or not but I think I found it.

You need to open **Settings** -> **Networks** -> **Localhost:8545**
And change the Chain ID to match your error so for my case I changed it to `31337`

![image](https://user-images.githubusercontent.com/89672487/150066879-695d16fe-cd4d-477c-bdab-9082bb2223f9.png)

**Comment by DiscrimIsPog** [comment]
That worked! Thanks!
